import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Funnel_Display } from "next/font/google";

const funnelDisplay = Funnel_Display({
  subsets: ["latin"],
  variable: "--font-funnel-display", // Optional, for custom CSS variable
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-transparent h-[100%]">
      <body
        className={`h-full ${funnelDisplay.variable} ${funnelDisplay.variable} antialiased`}
        
      >
        {children}
      </body>
    </html>
  );
}
